# Fasce orarie configurabili (ore del giorno, 0-23). "notte" attraversa la mezzanotte.
time_windows:
  notte: {start: 20, end: 5}
  giorno: {start: 5, end: 16}
  sera: {start: 16, end: 20}

# Lista di simulazioni: ogni simulazione pu√≤ sovrascrivere duration_days, n_nests, nest_selection_weights, distributions
simulations:
  - name: "pre_1"
    duration_days: 18
    n_nests: 4
    nest_selection_weights: [0.56479076, 0.28080808, 0.11457431, 0.03982684]  # Da compilare manualmente
    distributions:
      notte:
        gamma: {shape: 1.106007044, rate: 0.005501793}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.00008374183  # 0.301470588 / 3600
      giorno:
        gamma: {shape: 0.905118183, rate: 0.009922638}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.004869726680555556  # 17.53101605 / 3600
      sera:
        gamma: {shape: 0.77139994, rate: 0.012763672}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.000343137255  # 1.235294118 / 3600

  - name: "pre_2"
    duration_days: 18
    n_nests: 4
    nest_selection_weights: [0.592635547, 0.385329081, 0.017396347, 0.004639026]  # Da compilare manualmente
    distributions:
      notte:
        gamma: {shape: 0.886537524, rate: 0.004286278}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.00007148692805555555  # 0.257352941 / 3600
      giorno:
        gamma: {shape: 0.945286247, rate: 0.008681838}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.004803921569444445  # 17.29411765 / 3600
      sera:
        gamma: {shape: 0.650365796, rate: 0.011751648}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.000343137255  # 1.235294118 / 3600

  - name: "post_1"
    duration_days: 220
    n_nests: 4
    nest_selection_weights: [0.46050347, 0.29839410, 0.15169271, 0.08940972]  # Da compilare manualmente
    distributions:
      notte:
        gamma: {shape: 0.963698459, rate: 0.007471344}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.00002149470888888889  # 0.077380952 / 3600
      giorno:
        gamma: {shape: 0.88787549, rate: 0.007217957}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.0008611912777777778  # 3.100288600 / 3600
      sera:
        gamma: {shape: 0.831076429, rate: 0.009532013}
        mixture_prob: 0.97
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.00005511463861111111  # 0.198412699 / 3600

  - name: "post_2"
    duration_days: 220
    n_nests: 4
    nest_selection_weights: [0.50000000, 0.29054477, 0.14788144, 0.06157378]  # Da compilare manualmente
    distributions:
      notte:
        gamma: {shape: 0.977153483, rate: 0.006177577}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.00012541118416666667  # 0.451480263 / 3600
      giorno:
        gamma: {shape: 0.902203913, rate: 0.006902258}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.0014197900052777778  # 5.111244019 / 3600
      sera:
        gamma: {shape: 0.899557473, rate: 0.008011554}
        mixture_prob: 0.98
        uniform: {min: 1000, max: 10800}
        arrival_rate_per_second: 0.0001265533625  # 0.455592105 / 3600
